all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    servers:
      hosts:
        web01:
          ansible_host: 207.244.244.247
          ansible_user: ubuntu
          deploy_path: /home/ubuntu/deploy
