- name: Deploy Benefit Elect of Texas website via Docker
  hosts: web01
  become: yes
  tasks:
    - name: Update The System
      apt:
        update_cache: yes
      become: yes

    - name: Prerequisites Packages Installation
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip

    - name: Install python packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - requests

    - name: Add The GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add The Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Docker Installation
      apt:
        name: docker-ce
        state: present
      become: yes

    - name: Docker service Start
      service:
        name: docker
        state: started
      become: yes

    - name: Log into DockerHub
      docker_login:
        username: '{{ lookup("env", "DOCKERHUB_USERNAME") }}'
        password: '{{ lookup("env", "DOCKERHUB_PASSWORD") }}'

    - name: Creates directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /root/beoftexas/data
        - /root/beoftexas/data/nginx
        - /root/beoftexas/data/certbot
        - /root/beoftexas/secret

    - name: copy secrets
      copy:
        src: "../secret/{{ item }}"
        dest: "/root/beoftexas/secret/{{ item }}"
      loop:
      - beoftexas_db_pw.txt
      - beoftexas_db_root_pw.txt

          #    - name: copy Docker Compose files
          #      copy:
          #        src: "{{ item }}"
          #        dest: "/root/beoftexas/{{ item }}"
          #      loop:
          #      - docker-compose.yaml


          #    - name: copy nginx config
          #      copy:
          #        src: "{{ item }}"
          #        dest: "/root/beoftexas/{{ item }}"
          #      loop:
          #      - data/nginx/app.conf

          #    - name: Create and start services
          #      community.docker.docker_compose_v2:
          #        project_src: /root/beoftexas
          #      register: output
          #

    - name: copy scripts
      copy:
        src: "scripts/{{ item }}"
        dest: "/root/beoftexas/{{ item }}"
      loop:
        - backup.sh

    - name: Create backup cronjob
      ansible.builtin.cron:
        name: "check dirs"
        minute: "0"
        hour: "0"
        job: "/root/beoftexas/backup.sh > /dev/null"
