---
- name: Force restore beoftexas database from backup (Demo)
  hosts: demo
  gather_facts: false
  become: true
  vars:
    deploy_path: /home/ubuntu/deploy/beoftexas
    s3_access_key: "{{ lookup('env', 'CONTABO_S3_ACCESS_KEY') }}"
    s3_secret_key: "{{ lookup('env', 'CONTABO_S3_SECRET_KEY') }}"
    s3_bucket: "{{ lookup('env', 'CONTABO_S3_BUCKET') | default('beoftexas-backup', true) }}"
    env_file: "{{ deploy_path }}/.env"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install unzip utility
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Check if AWS CLI is already installed
      ansible.builtin.command: aws --version
      register: aws_cli_check
      changed_when: false
      failed_when: false

    - name: Download AWS CLI v2 installer
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'
      when: aws_cli_check.rc != 0

    - name: Unzip AWS CLI installer
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: true
      when: aws_cli_check.rc != 0

    - name: Install AWS CLI v2
      ansible.builtin.command: /tmp/aws/install
      when: aws_cli_check.rc != 0

    - name: Clean up AWS CLI installer files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/awscliv2.zip
        - /tmp/aws
      when: aws_cli_check.rc != 0

    - name: Download database backup from Contabo S3
      ansible.builtin.shell: |
        AWS_ACCESS_KEY_ID="{{ s3_access_key }}" \
        AWS_SECRET_ACCESS_KEY="{{ s3_secret_key }}" \
        aws s3 cp s3://{{ s3_bucket }}/beoftexas_latest.sql.gz /tmp/beoftexas_latest.sql.gz \
          --endpoint-url https://usc1.contabostorage.com
      no_log: false
      changed_when: true

    - name: Verify backup file was downloaded
      ansible.builtin.stat:
        path: /tmp/beoftexas_latest.sql.gz
      register: backup_file
      failed_when: not backup_file.stat.exists or backup_file.stat.size == 0

    - name: Display backup file info
      ansible.builtin.debug:
        msg: "Backup file downloaded: {{ backup_file.stat.size }} bytes"

    - name: Stop beoftexas application service
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose stop web
      register: stop_result
      changed_when: true

    - name: Display stop result
      ansible.builtin.debug:
        msg: "Beoftexas service stopped"

    - name: Wait for MariaDB to be ready
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose exec -T mariadb mariadb -u root -p$(grep "^DB_ROOT_PASSWORD=" {{ env_file }} | cut -d'=' -f2-) -e "SELECT 1" 2>&1
      register: db_ready
      until: db_ready.rc == 0
      retries: 30
      delay: 2
      changed_when: false
      no_log: false

    - name: Drop existing beoftexas database
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose exec -T mariadb mariadb -u root -p$(grep "^DB_ROOT_PASSWORD=" {{ env_file }} | cut -d'=' -f2-) -e "DROP DATABASE IF EXISTS beoftexas;"
      register: drop_result
      changed_when: true
      no_log: true

    - name: Display database drop status
      ansible.builtin.debug:
        msg: "Database dropped successfully"

    - name: Create fresh beoftexas database
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose exec -T mariadb mariadb -u root -p$(grep "^DB_ROOT_PASSWORD=" {{ env_file }} | cut -d'=' -f2-) -e "CREATE DATABASE beoftexas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      register: create_result
      changed_when: true
      no_log: true

    - name: Display database creation status
      ansible.builtin.debug:
        msg: "Database created successfully"

    - name: Test backup file integrity
      ansible.builtin.shell: gunzip -t /tmp/beoftexas_latest.sql.gz
      register: integrity_check
      changed_when: false
      failed_when: integrity_check.rc != 0

    - name: Restore database from backup
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        gunzip -c /tmp/beoftexas_latest.sql.gz | docker compose exec -T mariadb mariadb -u root -p$(grep "^DB_ROOT_PASSWORD=" {{ env_file }} | cut -d'=' -f2-) beoftexas
      register: restore_result
      changed_when: true
      no_log: false

    - name: Display restore completion
      ansible.builtin.debug:
        msg: "Database restoration completed"

    - name: Verify database has tables after restore
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose exec -T mariadb mariadb -u root -p$(grep "^DB_ROOT_PASSWORD=" {{ env_file }} | cut -d'=' -f2-) beoftexas -e "SHOW TABLES;" 2>/dev/null | wc -l
      register: table_count
      changed_when: false
      no_log: true
      failed_when: (table_count.stdout | int) <= 1

    - name: Display table count
      ansible.builtin.debug:
        msg: "Database restored successfully with {{ (table_count.stdout | int) - 1 }} tables"

    - name: Restart beoftexas application service
      ansible.builtin.shell: |
        cd {{ deploy_path }} && \
        docker compose start web
      register: start_result
      changed_when: true

    - name: Display restart status
      ansible.builtin.debug:
        msg: "Beoftexas service restarted successfully"

    - name: Clean up temporary backup file
      ansible.builtin.file:
        path: /tmp/beoftexas_latest.sql.gz
        state: absent

    - name: Display final status
      ansible.builtin.debug:
        msg:
          - "====================================="
          - "Database restore completed successfully!"
          - "====================================="
